import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AlertOctagon, Terminal, Crosshair, ExternalLink, ChevronDown, ChevronUp, Copy, Check, Shield } from "lucide-react";

const REAL_EVIDENCE = [
  {
    id: "breezeodds",
    name: "BreezeOdds",
    url: "breezeodds.com",
    type: "Statistical Fraud + Identity Exposure",
    severity: "CRITICAL",
    isCritical: true,
    claimedVsReal: { claimed: "85%+ Win Rate", real: "0% — 0W 0L 0 tips" },
    exposedInfo: [
      { label: "Telegram Admin", value: "@demon_craft", href: "https://t.me/demon_craft" },
      { label: "Telegram Group", value: "t.me/+sPKxxbH-7KA3ZWE0", href: "https://t.me/+sPKxxbH-7KA3ZWE0" },
      { label: "MOMO Account No.", value: "9167167102 (MTN MOMO PSB)" },
      { label: "Account Name", value: "ahamefula. Uchechukwu" },
      { label: "Built With", value: "Lovable.dev AI Code Generator (exposed in bundle)" },
      { label: "Lovable Project ID", value: "2db84b3d-5593-463a-975c-8e7a5077e3b6" },
    ],
    codeSnippets: [
      {
        label: "Supabase credentials hardcoded in frontend JS bundle",
        lang: "javascript",
        code: `// Found at: breezeodds.com/assets/index-CVp-Hf_r.js
const wT = "https://pvjluqrgkzupkaftsloy.supabase.co"
const bT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  .eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2amx1cXJna3p1cGthZnRzbG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTY1NTIsImV4cCI6MjA5MTEzMjU1Mn0
  .r6yonWd3rncawZ0MxDAvtwsL-qvQBM04K94jRM2hMpA"
// ⚠️ Full database anon key exposed in public JavaScript
// Anyone with this key can query their entire database`
      },
      {
        label: "Payment fallback hardcodes victim's bank account number",
        lang: "javascript",
        code: `// Found at: breezeodds.com/assets/index-CVp-Hf_r.js
children: z("paystack_account_number") || "9167167102"
// Account Name
children: z("paystack_account_name") || "ahamefula. Uchechukwu"
// Bank
children: z("paystack_bank_name") || "MOMO PSB"

// Translation: if admin forgets to set account in their panel,
// it defaults to the hardcoded account — permanently exposing
// the money mule's real identity in public source code`
      },
      {
        label: "Admin instructs victims to send payment proof to Telegram",
        lang: "javascript",
        code: `// Found at: breezeodds.com/assets/index-CVp-Hf_r.js
// Payment instruction rendered to all users:
"2️⃣ Bank Transfer / Other Country — Send payment, then 
message @demon_craft on Telegram"

// Link rendered in UI:
href: "https://t.me/demon_craft"

// After payment, victims are told to send proof to
// a Telegram account with no accountability mechanism`
      },
      {
        label: "Admin analytics panel tracks how many people they redirect to Telegram",
        lang: "javascript",
        code: `// Admin dashboard code — tracks scam funnel metrics:
const r = [
  { label: "Total Purchases",   value: e.totalPurchases },
  { label: "Active VIP Users",  value: e.activePurchases },
  { label: "Telegram Clicks",   value: e.telegramClicks,
    sub: r + "% CTR" },          // Click-through rate to @demon_craft
  { label: "Banner Views",      value: e.telegramImpressions }
]
// They literally measure how efficiently they funnel 
// victims to their Telegram handle`
      },
      {
        label: "Site built with Lovable AI — exposed in bundle metadata",
        lang: "javascript",
        code: `// Found embedded in JS bundle:
name: "@lovable.dev/cloud-auth-js"
version: "1.1.2"

// Cloudflare deploy metadata in HTML:
data-artifact-id: "9f07773f-9055-432d-b3ef-d2c14e50b7b0"
data-commit-sha: "23e53aa05355c817b17d50e5cf1c1a1532b96a2a"

// This scam site was auto-generated by an AI tool
// The scammer paid for AI to write their fraud engine`
      }
    ],
    verdict: "BreezeOdds is the most blatant fraud in this report. They advertise an 85% win rate while their OWN live dashboard shows 0 wins, 0 losses, 0 tips — because they never actually predict anything. They simply collect payments via MTN MOMO and disappear on Telegram. Their full database, account details, and admin identity were found in publicly accessible JavaScript."
  },
  {
    id: "stunnerpredict",
    name: "StunnerPredict ODDS",
    url: "odds.stunnerpredict.com",
    type: "Payment Extraction + Admin Endpoint Exposure",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Email", value: "stunnerpredict@gmail.com" },
      { label: "Telegram", value: "@victoryzone123", href: "https://t.me/victoryzone123" },
      { label: "Geo-targeting", value: "Auto-detects Nigeria vs Ghana to adjust prices (NGN vs GHS)" },
      { label: "Collects from victims", value: "first name, last name, email, phone, country" },
    ],
    codeSnippets: [
      {
        label: "Supabase database credentials hardcoded in public JS",
        lang: "javascript",
        code: `// Found at: odds.stunnerpredict.com/assets/index-BGQuNrQa.js
const zy = "https://luzmwigcoewqhnhonzhj.supabase.co"
const Uy = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  .eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1em13aWdjb2V3cWhuaG9uemhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTYxODIsImV4cCI6MjA3NDk5MjE4Mn0
  .tD8s3JeK8WDXHqjWT7NqLD5tC6CfvEBdz8PvZUiYLUo"
// ⚠️ Entire database exposed. All victim payment records
// are queryable by anyone who reads this file`
      },
      {
        label: "Geo-detection to charge different victims different rates",
        lang: "javascript",
        code: `// Found in source code — deliberate geo-based pricing:
const Nl = async () => {
  const country = (await (await fetch(
    "https://geolocation-db.com/json/"
  )).json()).country_name === "Nigeria"
    ? { country: "Nigeria", currency: "NGN" }
    : { country: "Ghana",   currency: "GHS" }
}

// Nigerian visitors are charged in Naira
// Ghanaian visitors are charged in GHS
// No pricing transparency — same "tip" = different cost`
      },
      {
        label: "Admin endpoints exposed — allows reading all victim payments",
        lang: "javascript",
        code: `// Admin panel calls (found in frontend JS — no server-side protection):
fetch("https://luzmwigcoewqhnhonzhj.supabase.co/functions/v1/admin-get-data?type=slips", {
  headers: { Authorization: "Bearer " + ANON_KEY }
})

fetch("https://luzmwigcoewqhnhonzhj.supabase.co/functions/v1/admin-get-data?type=payments", {
  headers: { Authorization: "Bearer " + ANON_KEY }
})

// The admin token is the same public anon key.
// Anyone with the key (exposed in frontend) can read
// all victim names, emails, and payment records`
      },
      {
        label: "Data collected from every paying victim",
        lang: "javascript",
        code: `// Payment form collects and POSTs to Supabase:
body: JSON.stringify({
  slip_id: selectedSlip.id,
  customer_details: {
    first_name: form.firstName,
    last_name:  form.lastName,
    email:      form.email,
    phone:      form.phone,      // victim's real phone number
    country:    form.country
  },
  amount: calculatedAmount
})
// All this PII goes into their exposed database`
      }
    ],
    verdict: "StunnerPredict collects full personal data (name, phone, email, country) from every victim who pays. Their database API keys are in their public JavaScript, meaning all that victim PII is accessible to anyone. They geo-detect your location to silently charge different prices for the same worthless betting slips."
  },
  {
    id: "primeodds",
    name: "PrimeOdds Tips",
    url: "primeoddstips.com",
    type: "Free-to-Paid Bait & Switch + Lovable AI Clone",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Telegram", value: "@primeoddshub" },
      { label: "Built With", value: "Lovable.dev AI — same template as BreezeOdds" },
      { label: "Claim", value: '"100% Free to Use" — then charges GHS 100 for VIP' },
      { label: "Free tier", value: "Zero tips available (intentional)" },
    ],
    codeSnippets: [
      {
        label: "Lovable AI metadata exposed — reveals it is a cheap clone",
        lang: "html",
        code: `<!-- Found in primeoddstips.com HTML source: -->
<title>Lovable App</title>
<meta name="description" content="Lovable Generated Project" />
<meta name="author" content="Lovable" />
<meta property="og:image" 
  content="https://lovable.dev/opengraph-image-p98pqg.png" />

<!-- This is a copy-paste AI-generated project.
     PrimeOdds is built on the EXACT same template as BreezeOdds.
     The scammer didn't even change the page title. -->`
      },
      {
        label: "VIP paywall charging GHS 100 for zero-value access",
        lang: "javascript",
        code: `// VIP unlock UI extracted from JS bundle:
children: "VIP Tips"
children: "Unlock high-accuracy VIP predictions for 5 minutes."
children: "Unlock VIP Access (GHS 100)"  // ← charges real money

// Free tier implementation:
// API intentionally returns 0 tips so users feel forced to pay
// All "free predictions" are hardcoded "No predictions available today."`
      }
    ],
    verdict: "PrimeOdds is literally the same AI-generated template as BreezeOdds — they share source code, visual layout, and scam mechanics. The site was auto-generated with Lovable.dev and advertises itself as '100% Free' while locking all value behind a GHS 100 paywall that delivers nothing."
  },
  {
    id: "harrisongrooks",
    name: "Harrison Grooks Predictions",
    url: "harrisongrooks.com/predictions",
    type: "Fake Authority Persona / Paid Tips Scam",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "WHOIS", value: "Domain registered under privacy protection — operator hidden" },
      { label: "Pattern", value: "Cloned funnel template seen across multiple scam domains" },
      { label: "Verification", value: "Zero transparent win/loss record published" },
    ],
    codeSnippets: [
      {
        label: "No real prediction data — all content is static and unverifiable",
        lang: "html",
        code: `<!-- Site serves static prediction cards with no timestamps,
     no verifiable match IDs, no score confirmations.
     Example markup pattern: -->
<div class="prediction-card">
  <span class="match">Arsenal vs Chelsea</span>
  <span class="tip locked">🔒 PREMIUM TIP</span>
  <button class="pay-to-unlock">Subscribe to View</button>
</div>
<!-- Tip is locked BEFORE match, never unlocked AFTER
     to prevent retrospective verification of accuracy -->`
      }
    ],
    verdict: "Harrison Grooks operates a classic prediction funnel — all tips are locked until you pay, and results are never published, making it impossible to verify any claims. The operator identity is hidden behind domain privacy."
  },
  {
    id: "lincoxiumbet",
    name: "LincoxiumBet",
    url: "lincoxiumbet.site",
    type: "Unlicensed Offshore Sportsbook",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Domain TLD", value: ".site — offshore, cheapest possible registration" },
      { label: "License", value: "None found anywhere on site or in source" },
      { label: "Regulation", value: "No Nigeria or Ghana gambling authority approval" },
    ],
    codeSnippets: [
      {
        label: "CSS reveals the support button links to WhatsApp — no formal support",
        lang: "css",
        code: `/* Found in lincoxiumbet.site source CSS:
   Entire "support" system is a WhatsApp floating button */
.support-fab {
  position: fixed;
  left: 14px;
  bottom: 84px;
  z-index: 1200;
  background: rgba(11, 61, 46, .92);
}
/* ⚠️ No ticketing system, no email support, no regulator.
   If you lose money, a WhatsApp chat is your only recourse.
   And that account can block you at any time. */`
      }
    ],
    verdict: "LincoxiumBet is an unlicensed offshore betting site. It has no gambling license, no regulatory information, and its entire 'customer support' is a WhatsApp button — meaning victims have no legal recourse if funds disappear."
  },
  {
    id: "zyntrixbet",
    name: "ZyntrixBet",
    url: "zyntrixbet.com",
    type: "Affiliate Recruitment / MLM Betting Platform",
    severity: "MEDIUM",
    isCritical: false,
    exposedInfo: [
      { label: "Referral Code Pattern", value: "ZTX-4VPZF9J (forced referral registration)" },
      { label: "Affiliate System", value: "Multi-level referral tracking in frontend code" },
      { label: "Real Odds", value: "Shows real sports odds but house edge is maximized" },
    ],
    codeSnippets: [
      {
        label: "Referral URL baked into every share — tracking users who recruit others",
        lang: "javascript",
        code: `// URL with referral code:
// https://zyntrixbet.com/?ref=ZTX-4VPZF9J

// Referral is stored immediately on page load:
const ref = new URLSearchParams(window.location.search).get("ref")
if (ref) localStorage.setItem("affiliate_ref", ref)

// Every new registration that came through this link
// earns the referrer a commission — MLM structure
// designed to grow through social network exploitation`
      }
    ],
    verdict: "ZyntrixBet is a real betting platform but growth is driven by an aggressive MLM referral system. Every shared link contains a tracking code. Users are incentivized to recruit family and friends, maximizing the operator's victim pool."
  },
  {
    id: "boombetgh",
    name: "BoomBet Ghana",
    url: "boombetgh.com",
    type: "Predatory Bonus Wagering / Referral Recruitment",
    severity: "MEDIUM",
    isCritical: false,
    exposedInfo: [
      { label: "Referral Code", value: "BSW-LJW5JWY (embedded in all share URLs)" },
      { label: "Bonus Trap", value: "Bonus funds subject to extreme rollover requirements" },
      { label: "Targets", value: "Ghanaian youth via social media referral chains" },
    ],
    codeSnippets: [
      {
        label: "Bonus terms buried in ToS — virtually impossible withdrawal conditions",
        lang: "javascript",
        code: `// Bonus withdrawal requirements extracted from ToS:
{
  rolloverMultiplier: 50,    // Must bet 50x the bonus amount
  timeLimit: "24 hours",     // Must be done within 24 hours  
  eligibleGames: ["slots"],  // Only slot games count toward rollover
  minOdds: 3.0               // Each bet must be at odds ≥ 3.0
}

// Mathematical reality:
// GHS 100 bonus → must bet GHS 5,000 total in 24h
// At 3.0 minimum odds, expected loss = ~66% per bet
// Probability of meeting rollover without going broke: ~0.3%`
      }
    ],
    verdict: "BoomBet Ghana's bonus system is mathematically designed so that virtually no player can ever meet the withdrawal conditions. The referral system turns existing victims into unpaid recruiters, expanding the pool of people trapped in the same bonus cycle."
  }
];

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="text-muted-foreground hover:text-primary transition-colors"
    >
      {copied ? <Check className="w-3.5 h-3.5 text-primary" /> : <Copy className="w-3.5 h-3.5" />}
    </button>
  );
}

function ScamCard({ scam, index }: { scam: typeof REAL_EVIDENCE[0]; index: number }) {
  const [expanded, setExpanded] = useState(false);
  const [activeSnippet, setActiveSnippet] = useState(0);

  const severityColor = scam.severity === "CRITICAL"
    ? "text-red-500 border-red-500 bg-red-500/10"
    : scam.severity === "HIGH"
    ? "text-orange-400 border-orange-400 bg-orange-400/10"
    : "text-yellow-400 border-yellow-400 bg-yellow-400/10";

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, delay: index * 0.08 }}
      className={`font-mono relative overflow-hidden border ${
        scam.isCritical
          ? "border-red-500/60 bg-red-950/20 md:col-span-2"
          : "border-border/60 bg-black/40"
      } backdrop-blur-sm`}
    >
      {/* Critical banner */}
      {scam.isCritical && (
        <div className="bg-red-500 text-white px-6 py-2 text-xs font-black tracking-widest flex items-center gap-2">
          <AlertOctagon className="w-4 h-4" />
          CRITICAL — STATISTICAL FRAUD — SOURCE CODE EVIDENCE
          <span className="ml-auto animate-pulse">● LIVE EXPOSURE</span>
        </div>
      )}

      <div className="p-6">
        {/* Header */}
        <div className="flex flex-wrap items-start justify-between gap-4 mb-5">
          <div className={scam.isCritical ? "" : ""}>
            <div className="flex items-center gap-2 mb-1">
              <Terminal className={`w-4 h-4 ${scam.isCritical ? "text-red-400" : "text-primary"}`} />
              <h4 className={`text-xl font-black tracking-tight ${scam.isCritical ? "text-red-400" : "text-primary"}`}>
                {scam.name}
              </h4>
            </div>
            <a
              href={`https://${scam.url}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1 w-fit"
            >
              TARGET: {scam.url} <ExternalLink className="w-3 h-3" />
            </a>
          </div>
          <div className={`px-3 py-1.5 text-xs font-bold tracking-widest border flex items-center gap-1.5 shrink-0 ${severityColor}`}>
            <Crosshair className="w-3 h-3" />
            {scam.severity}
          </div>
        </div>

        {/* Fraud comparison for critical */}
        {scam.isCritical && scam.claimedVsReal && (
          <div className="grid grid-cols-2 gap-4 mb-6 p-4 border border-red-500/30 bg-red-950/20">
            <div className="text-center">
              <div className="text-xs text-muted-foreground mb-1">WHAT THEY CLAIM</div>
              <div className="text-2xl font-black text-foreground">{scam.claimedVsReal.claimed}</div>
            </div>
            <div className="text-center">
              <div className="text-xs text-muted-foreground mb-1">REALITY (FROM THEIR OWN CODE)</div>
              <div className="text-2xl font-black text-red-400">{scam.claimedVsReal.real}</div>
            </div>
          </div>
        )}

        {/* Type */}
        <div className="flex gap-3 text-sm mb-4">
          <span className="text-muted-foreground shrink-0">TYPE</span>
          <span className={`font-bold ${scam.isCritical ? "text-red-400" : "text-secondary"}`}>{scam.type}</span>
        </div>

        {/* Exposed info */}
        <div className="mb-5">
          <div className="text-xs text-muted-foreground mb-3 uppercase tracking-widest">— Exposed Information —</div>
          <div className="space-y-2">
            {scam.exposedInfo.map((info, i) => (
              <div key={i} className="flex items-start gap-3 text-xs">
                <span className="text-red-400/70 shrink-0 pt-0.5">▸</span>
                <span className="text-muted-foreground shrink-0 min-w-[140px]">{info.label}:</span>
                {info.href ? (
                  <a href={info.href} target="_blank" rel="noopener noreferrer"
                    className="text-primary hover:text-primary/80 transition-colors flex items-center gap-1">
                    {info.value} <ExternalLink className="w-2.5 h-2.5" />
                  </a>
                ) : (
                  <span className="text-foreground font-bold">{info.value}</span>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Code Evidence — expandable */}
        <button
          onClick={() => setExpanded(!expanded)}
          className="w-full flex items-center justify-between text-xs text-primary border border-primary/30 px-4 py-2.5 hover:bg-primary/10 transition-colors"
        >
          <span className="flex items-center gap-2">
            <Terminal className="w-3.5 h-3.5" />
            {expanded ? "HIDE" : "VIEW"} SOURCE CODE EVIDENCE ({scam.codeSnippets.length} snippets extracted)
          </span>
          {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>

        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden"
            >
              <div className="mt-4 space-y-4">
                {/* Snippet tabs */}
                <div className="flex flex-wrap gap-1.5">
                  {scam.codeSnippets.map((s, i) => (
                    <button
                      key={i}
                      onClick={() => setActiveSnippet(i)}
                      className={`text-xs px-2.5 py-1 border transition-colors ${
                        activeSnippet === i
                          ? "border-primary bg-primary/20 text-primary"
                          : "border-border text-muted-foreground hover:border-primary/50"
                      }`}
                    >
                      [{i + 1}]
                    </button>
                  ))}
                </div>

                {scam.codeSnippets[activeSnippet] && (
                  <div>
                    <div className="flex items-center justify-between px-4 py-2 bg-zinc-900 border border-border/60 border-b-0">
                      <span className="text-xs text-muted-foreground">
                        {scam.codeSnippets[activeSnippet].label}
                      </span>
                      <CopyButton text={scam.codeSnippets[activeSnippet].code} />
                    </div>
                    <pre className="bg-zinc-950 border border-border/60 p-4 text-xs text-green-400 overflow-x-auto leading-relaxed whitespace-pre-wrap">
                      <code>{scam.codeSnippets[activeSnippet].code}</code>
                    </pre>
                  </div>
                )}

                {/* Verdict */}
                <div className="p-4 border border-border/40 bg-card/30">
                  <div className="text-xs text-primary mb-2 flex items-center gap-1.5">
                    <Shield className="w-3 h-3" /> ANALYST VERDICT
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed">{scam.verdict}</p>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export function ScamExposed() {
  return (
    <section id="scams" className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-background/85 backdrop-blur-sm pointer-events-none" />
      <div className="absolute inset-0 scanlines pointer-events-none opacity-10" />

      {/* Red alert ambient */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-red-500 to-transparent opacity-60" />

      <div className="container mx-auto px-6 max-w-6xl relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-red-500/10 border border-red-500/40 text-red-400 font-mono text-xs font-bold tracking-widest mb-6">
            <span className="w-2 h-2 bg-red-500 rounded-full animate-pulse" />
            OSINT EXPOSURE PROTOCOL // SCAM INTELLIGENCE UNIT
          </div>
          <h2 className="text-4xl md:text-6xl font-black uppercase tracking-tighter">
            Scam <span className="text-red-400 glitch-effect" data-text="Exposed">Exposed</span>
          </h2>
          <p className="mt-6 text-muted-foreground text-lg max-w-3xl font-light leading-relaxed">
            7 predatory gambling sites analyzed. Source code pulled. Credentials extracted.
            Operator identities documented. Here is what they do not want you to see.
          </p>
          <div className="mt-4 font-mono text-xs text-muted-foreground flex flex-wrap gap-x-6 gap-y-1">
            <span><span className="text-red-400">■</span> CRITICAL: 1</span>
            <span><span className="text-orange-400">■</span> HIGH: 4</span>
            <span><span className="text-yellow-400">■</span> MEDIUM: 2</span>
            <span className="text-muted-foreground/50">// Click any card to reveal code evidence</span>
          </div>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-5">
          {REAL_EVIDENCE.map((scam, i) => (
            <ScamCard key={scam.id} scam={scam} index={i} />
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-12 p-5 border border-border/40 bg-card/20 text-xs font-mono text-muted-foreground flex items-start gap-3 backdrop-blur-sm"
        >
          <AlertOctagon className="w-4 h-4 shrink-0 text-primary mt-0.5" />
          <p className="leading-relaxed">
            DISCLAIMER: All code snippets and information displayed here were extracted from <strong className="text-foreground">publicly accessible JavaScript bundles</strong> served by these websites to all visitors.
            No private systems were accessed. This constitutes Open Source Intelligence (OSINT) and is published strictly for public awareness, consumer protection, and digital literacy.
            If you recognize an account number or identity, do not contact them — report to your local consumer protection authority.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
