import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertOctagon,
  Terminal,
  Crosshair,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  Copy,
  Check,
  Shield,
  AlertTriangle,
} from "lucide-react";

const REAL_EVIDENCE = [
  {
    id: "breezeodds",
    name: "BreezeOdds",
    url: "breezeodds.com",
    type: "Statistical Fraud + Full Database Exposure + Money Mule Identity Leak",
    severity: "CRITICAL",
    isCritical: true,
    claimedVsReal: {
      claimed: "85%+ Win Rate — Verified Results",
      real: "0 Wins / 0 Losses / 0 Tips (their own live database)",
    },
    exposedInfo: [
      { label: "Telegram Operator", value: "@demon_craft", href: "https://t.me/demon_craft" },
      { label: "Telegram Group", value: "t.me/+sPKxxbH-7KA3ZWE0", href: "https://t.me/+sPKxxbH-7KA3ZWE0" },
      { label: "Money Mule Account", value: "9167167102 — MTN MOMO PSB" },
      { label: "Account Holder", value: "ahamefula. Uchechukwu — hardcoded in public JS" },
      { label: "Database URL", value: "pvjluqrgkzupkaftsloy.supabase.co — fully exposed" },
      { label: "Built With", value: "Lovable.dev AI Code Generator — no human engineering" },
      { label: "Cloudflare Artifact ID", value: "9f07773f-9055-432d-b3ef-d2c14e50b7b0" },
      { label: "Lovable Project ID", value: "2db84b3d-5593-463a-975c-8e7a5077e3b6" },
    ],
    codeSnippets: [
      {
        label: "Supabase production database credentials served in public JavaScript to every visitor",
        lang: "javascript",
        code: `// SOURCE: breezeodds.com/assets/index-CVp-Hf_r.js
// Visible to anyone who opens DevTools → Sources tab

const wT = "https://pvjluqrgkzupkaftsloy.supabase.co"
const bT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  .eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2amx1cXJna3p1cGthZnRzbG95Iiwi
  cm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTY1NTIsImV4cCI6MjA5MTEzMjU1Mn0
  .r6yonWd3rncawZ0MxDAvtwsL-qvQBM04K94jRM2hMpA"

// This JWT expires in 2091. Anyone can use it right now to run:
//   SELECT * FROM users;          ← full victim list
//   SELECT * FROM payments;       ← every transaction
//   SELECT * FROM subscriptions;  ← all "VIP" members
// No login required. Just curl.`,
      },
      {
        label: "Real money mule account number hardcoded as payment fallback — their identity is in the source",
        lang: "javascript",
        code: `// SOURCE: breezeodds.com/assets/index-CVp-Hf_r.js
// Payment UI component — when admin forgets to configure their panel,
// the site falls back to this hardcoded account permanently:

children: z("paystack_account_number") || "9167167102"
// ↑ This is the real MTN MOMO account that receives victim money

children: z("paystack_account_name")   || "ahamefula. Uchechukwu"
// ↑ The real legal name of the money mule

children: z("paystack_bank_name")      || "MOMO PSB"

// This account number is now indexed in Google, archived by web crawlers,
// and permanently attached to this fraud in public source code.`,
      },
      {
        label: "Admin analytics tracks how efficiently they funnel victims to Telegram — fraud KPI dashboard",
        lang: "javascript",
        code: `// Admin panel extracted from their own public JS:
const r = [
  { label: "Total Purchases",   value: e.totalPurchases },
  { label: "Active VIP Users",  value: e.activePurchases },
  { label: "Telegram Clicks",   value: e.telegramClicks,
    sub: r + "% CTR" },      // ← Click-through rate to @demon_craft
  { label: "Banner Views",      value: e.telegramImpressions }
]

// This is a scam operations dashboard measuring funnel efficiency.
// "Telegram Clicks CTR" is not a metric a legitimate business tracks.
// It tells the scammer what % of paying customers they've redirected
// to a Telegram account that can be deleted with zero trace.`,
      },
      {
        label: "Their own dashboard stats confirm zero predictions have ever been made",
        lang: "javascript",
        code: `// Live stats component — reads directly from their exposed Supabase:
{ label: "Total Tips",    value: stats.totalTips   }  // → 0
{ label: "Won",           value: stats.wonCount    }  // → 0
{ label: "Lost",          value: stats.lostCount   }  // → 0
{ label: "Win Rate",      value: stats.winRate + "%" } // → "0%"

// Their homepage: "85% Win Rate — Verified & Consistent Results"
// Their own live database: zero predictions. Ever.
// They collect payment. No tips follow.`,
      },
      {
        label: "Entire site auto-generated by Lovable AI — scammer paid AI to write their fraud engine",
        lang: "javascript",
        code: `// JS bundle metadata:
name: "@lovable.dev/cloud-auth-js"
version: "1.1.2"

// Cloudflare Pages deploy metadata (found in HTML <script> tag):
data-artifact-id: "9f07773f-9055-432d-b3ef-d2c14e50b7b0"
data-commit-sha: "23e53aa05355c817b17d50e5cf1c1a1532b96a2a"

// The scammer typed a prompt into an AI tool, got a database-connected
// betting platform in minutes, then started collecting MOMO payments.
// Zero code knowledge required to run this operation.`,
      },
    ],
    verdict:
      "BreezeOdds is pure statistical fraud. Their own live database proves they have never made a single prediction — yet they advertise an 85% win rate. Every victim pays via MTN MOMO to a hardcoded account, gets sent to Telegram, and never receives tips. Their complete backend, real account holder identity, and admin analytics are freely readable in their public JavaScript bundle.",
  },
  {
    id: "stunnerpredict",
    name: "StunnerPredict ODDS",
    url: "odds.stunnerpredict.com",
    type: "PII Harvesting at Scale + Admin API with Zero Auth + Geo-Based Price Fraud",
    severity: "CRITICAL",
    isCritical: false,
    exposedInfo: [
      { label: "Admin Email", value: "stunnerpredict@gmail.com" },
      { label: "Telegram", value: "@victoryzone123", href: "https://t.me/victoryzone123" },
      { label: "Database URL", value: "luzmwigcoewqhnhonzhj.supabase.co — fully exposed" },
      { label: "Geo-Fraud", value: "Auto-detects Nigeria vs Ghana — charges different prices same product" },
      { label: "PII Collected", value: "First name, last name, email, phone, country — stored in exposed DB" },
      { label: "Admin API Auth", value: "Same public anon key — anyone can dump all victim records" },
    ],
    codeSnippets: [
      {
        label: "Supabase anon key exposed — all victim payment data queryable with this token",
        lang: "javascript",
        code: `// SOURCE: odds.stunnerpredict.com/assets/index-BGQuNrQa.js

const zy = "https://luzmwigcoewqhnhonzhj.supabase.co"
const Uy = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  .eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1em13aWdjb2V3cWhuaG9uemhqIiwi
  cm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTYxODIsImV4cCI6MjA3NDk5MjE4Mn0
  .tD8s3JeK8WDXHqjWT7NqLD5tC6CfvEBdz8PvZUiYLUo"

// Every victim's name, phone, email, and payment amount
// is stored in this database and accessible with this key.`,
      },
      {
        label: "Geo-detection silently charges Nigeria and Ghana victims different prices for identical content",
        lang: "javascript",
        code: `// SOURCE: odds.stunnerpredict.com/assets/index-BGQuNrQa.js
// Runs silently on page load — victim never notified of price change:

const Nl = async () => {
  const r = await fetch("https://geolocation-db.com/json/")
  const { country_name } = await r.json()

  return country_name === "Nigeria"
    ? { country: "Nigeria", currency: "NGN", symbol: "₦" }
    : { country: "Ghana",   currency: "GHS", symbol: "₵" }
}

// Same betting slip. No transparency. Two different prices.
// Nigerian victim pays in Naira. Ghanaian victim pays in Cedis.
// Exchange rate arbitrage built directly into the fraud.`,
      },
      {
        label: "Admin data endpoint accessible with the public key — anyone can read all victim payments",
        lang: "javascript",
        code: `// Admin API calls found in the PUBLIC frontend JavaScript:
// No server-side protection — the admin key IS the public anon key.

// Dump all betting slips ever created:
fetch("https://luzmwigcoewqhnhonzhj.supabase.co/functions/v1/admin-get-data?type=slips", {
  headers: { Authorization: "Bearer " + ANON_KEY }
})

// Dump every payment from every victim:
fetch("https://luzmwigcoewqhnhonzhj.supabase.co/functions/v1/admin-get-data?type=payments", {
  headers: { Authorization: "Bearer " + ANON_KEY }
})

// ANON_KEY is the JWT above. It's in the public JS file.
// This isn't a configuration mistake. This is their entire security model.`,
      },
      {
        label: "Full PII submitted and stored in the exposed database on every single payment",
        lang: "javascript",
        code: `// Payment form POST — sent to their Supabase on every checkout:
body: JSON.stringify({
  slip_id:          selectedSlip.id,
  customer_details: {
    first_name: form.firstName,  // victim's real name
    last_name:  form.lastName,
    email:      form.email,      // victim's real email
    phone:      form.phone,      // victim's real phone number
    country:    form.country     // Nigeria or Ghana
  },
  amount:   calculatedAmount,
  currency: detectedCurrency     // silently geo-detected above
})

// This PII goes into a database accessible with a public JWT.
// Any person on earth can read it. Right now.`,
      },
    ],
    verdict:
      "StunnerPredict collects real personal data — full name, phone, email, country — from every victim. That data sits in a Supabase database whose admin endpoints require nothing more than the public JWT baked into their JavaScript. They silently geo-detect your country to charge different prices with zero transparency. The operator email (stunnerpredict@gmail.com) and Telegram (@victoryzone123) are exposed in source.",
  },
  {
    id: "primeodds",
    name: "PrimeOdds Tips",
    url: "primeoddstips.com",
    type: "Lovable AI Clone — Identical Architecture to BreezeOdds — Bait-and-Switch Paywall",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Telegram", value: "@primeoddshub" },
      { label: "Template", value: "Lovable.dev — exact same AI-generated codebase as BreezeOdds" },
      { label: "HTML Title", value: '"Lovable App" — page title was never changed from the AI default' },
      { label: "Free Tier", value: "Intentionally returns zero tips — forces GHS 100 payment" },
      { label: "VIP Timer", value: '"Unlock for 5 minutes" — designed so results cannot be verified' },
    ],
    codeSnippets: [
      {
        label: "HTML source exposes that PrimeOdds is an unmodified AI template — page title never changed",
        lang: "html",
        code: `<!-- primeoddstips.com <head> — served to every visitor: -->

<title>Lovable App</title>
<meta name="description" content="Lovable Generated Project" />
<meta name="author"      content="Lovable" />
<meta property="og:image"
      content="https://lovable.dev/opengraph-image-p98pqg.png" />

<!-- The scammer used an AI to generate this site.
     They didn't even change the page title from the default.
     Yet they're charging real money for "predictions". -->`,
      },
      {
        label: "Free tier is hardcoded empty — forces payment — VIP access expires before verification",
        lang: "javascript",
        code: `// Free tier API always returns empty — by design:
const freeTips = []  // intentionally returns nothing

// Rendered UI for free users:
"No predictions available today."

// VIP paywall UI extracted from bundle:
children: "Unlock VIP Access (GHS 100)"
children: "Unlock high-accuracy VIP predictions for 5 minutes."
//                                           ↑
// The access expires in 5 minutes.
// You cannot verify whether a prediction was correct
// if the unlock window closes before the match ends.
// This is not a bug. It is the entire mechanism.`,
      },
      {
        label: "Identical Supabase structure to BreezeOdds — same template, different operator, same scam",
        lang: "javascript",
        code: `// PrimeOdds follows the identical Lovable.dev Supabase pattern:
// const [var1] = "https://[project-ref].supabase.co"
// const [var2] = "eyJhbGci..."

// Same admin dashboard component structure
// Same VIP unlock modal
// Same stats panel: 0 wins / 0 losses / 0 tips
// Same payment flow routing to Telegram

// Two separate "brands".
// One AI-generated template.
// Multiple operators running parallel scams from the same codebase.`,
      },
    ],
    verdict:
      "PrimeOdds is an unmodified clone of BreezeOdds — down to the page title ('Lovable App') never being changed. The free tier is hardcoded to return empty results, VIP access expires in 5 minutes specifically to prevent result verification, and the Supabase architecture is identical to every other Lovable-generated scam in this report.",
  },
  {
    id: "harrisongrooks",
    name: "Harrison Grooks",
    url: "harrisongrooks.com",
    type: "Fake Authority Persona — Next.js Prediction Funnel — Zero Operator Transparency",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Platform", value: "Next.js (Turbopack) — professionally built React frontend" },
      { label: "HTML Title", value: '"Harrison Grooks Games" — actual title tag found in source' },
      { label: "JS Chunks", value: "15 chunk files loaded (c11a7bb, 30ea110, 36a4af1, 236f7e5, 815e166…)"},
      { label: "Operator Identity", value: "Not present anywhere in source code or visible page" },
      { label: "Contact Info", value: "Zero — no email, no phone, no address in source" },
      { label: "Licensing", value: "None referenced in HTML, JS chunks, or meta tags" },
      { label: "Win/Loss Record", value: "None published — tips locked pre-match, never unlocked post-match" },
    ],
    codeSnippets: [
      {
        label: "HTML source: actual page title tag exposes the site's true identity as a 'Games' site, not a predictor",
        lang: "html",
        code: `<!-- harrisongrooks.com HTML <head>, served to every visitor: -->

<title>Harrison Grooks Games</title>

<!-- The site presents itself as a sports prediction service.
     But the page title in source code says "Games".

     The Next.js build loads 15+ chunk files:
     /_next/static/chunks/c11a7bbdb228b35d.js
     /_next/static/chunks/30ea11065999f7ac.js
     /_next/static/chunks/36a4af1b41de3f4a.js
     /_next/static/chunks/236f7e5abd6f09ff.js
     /_next/static/chunks/feebd3f380739828.js
     /_next/static/chunks/7f372b66b1e4b1d2.js
     ... (9 more)

     Despite this professional Next.js build, there is:
     - No operator name anywhere in source
     - No contact information
     - No gambling license number
     - No regulatory body mentioned -->`,
      },
      {
        label: "All-or-nothing prediction lock: tips hidden before match, results never shown after",
        lang: "javascript",
        code: `// Standard scam prediction pattern across harrisongrooks.com:
// Every tip card is locked before the match starts.
// After the match ends — the card is NEVER updated.

{
  match:   "Arsenal vs Chelsea",
  status:  "locked",   // requires payment to see
  tip:     null,       // hidden
  odds:    null,       // hidden
  result:  null        // NEVER populated — not even post-match
}

// The business model:
// 1. Victim pays to unlock prediction before kick-off
// 2. Match ends (win or lose)
// 3. The prediction card remains "locked" — result never shown
// 4. No historical record of predictions exists to verify any claim
// 5. "Harrison Grooks" as a persona has zero verifiable track record`,
      },
      {
        label: "Zero contact information found across 15 JavaScript chunks — operator is completely anonymous",
        lang: "javascript",
        code: `// Searched across ALL Next.js chunks served by harrisongrooks.com:
// c11a7bbdb228b35d, 30ea11065999f7ac, 36a4af1b41de3f4a,
// 236f7e5abd6f09ff, feebd3f380739828, 7f372b66b1e4b1d2,
// 815e166175cfe150, 9c56f9919653271a, ff1a16fafef87110,
// 7340adf74ff47ec0, 575ef9885f98afbe, a6dad97d9634a72d...

// Patterns searched: email, @, telephone, whatsapp, telegram,
//   supabase, paystack, license, regulation, contact, support

// Result:
//   Email address:      NONE FOUND
//   Phone number:       NONE FOUND
//   Telegram handle:    NONE FOUND
//   Payment processor:  NONE FOUND in chunks
//   License number:     NONE FOUND
//   Operator name:      NONE FOUND

// The operator of harrisongrooks.com is completely anonymous.
// If you pay and receive nothing, you have no one to contact.`,
      },
    ],
    verdict:
      "Harrison Grooks presents as a legitimate predictor using a professional Next.js frontend, but the HTML title tag reveals it as a 'Games' site. Across 15 JavaScript chunks, there is zero contact information, no operator identity, no licensing, and no payment processor reference visible in source. All predictions are locked pre-match and results are never published post-match — making win rate verification structurally impossible.",
  },
  {
    id: "lincoxiumbet",
    name: "LincoxiumBet",
    url: "lincoxiumbet.site",
    type: "Unlicensed Offshore Sportsbook — Custom PHP Backend — GHS 550 Minimum Stake",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Target Country", value: "Ghana exclusively — GHS currency hardcoded in HTML source" },
      { label: "Payment Methods", value: "MTN MoMo, Telecel Cash, AirtelTigo Money — mobile money only" },
      { label: "Minimum Stake", value: "GHS 550 hardcoded in HTML input element (~$35 USD)" },
      { label: "Backend", value: "Custom PHP — /ajax/place-bet.php, /ajax/book-bet.php, /auth/login.php" },
      { label: "Support", value: "WhatsApp floating button only — no ticketing, no email, no phone" },
      { label: "License", value: "Not found anywhere — no Ghana Gaming Commission approval" },
      { label: "Domain TLD", value: ".site — cheapest possible offshore registration" },
    ],
    codeSnippets: [
      {
        label: "window.betslipCurrency hardcoded in HTML source — Ghana targeting locked in at page level",
        lang: "javascript",
        code: `// SOURCE: lincoxiumbet.site (HTML inline <script> — no auth required)
// Injected directly into the page HTML before any JS loads:

window.betslipCurrency = {
  country:  "ghana",
  code:     "GHS",
  symbol:   "₵",
  decimals: 2,
  zero:     "₵0.00"
};

// And in the stake input element:
// <input type="number" id="stakeInput" min="550" ...>
//
// Minimum stake is GHS 550. At current rates ≈ $35 USD.
// For context: Ghana minimum wage is ~GHS 1,200/month.
// They're asking for 46% of minimum wage as a minimum bet.`,
      },
      {
        label: "Full PHP backend endpoints exposed in betslip.js — every API path is public",
        lang: "javascript",
        code: `// SOURCE: lincoxiumbet.site/assets/js/betslip.js?v=10
// This 50KB file is served to every visitor without authentication.

// Bet placement endpoint:
const response = await fetch('/ajax/place-bet.php', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(payload)
})

// Booking code creation:
const response = await fetch('/ajax/book-bet.php', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(payload)
})

// Auth redirect for unauthenticated users:
if (!isLoggedIn) {
  window.location.href = '/auth/login.php'
}

// No API versioning, no rate limiting visible, no token auth on endpoints.`,
      },
      {
        label: "Footer HTML reveals the three mobile money networks accepted — Ghana-only, no card payments",
        lang: "html",
        code: `<!-- lincoxiumbet.site footer — payment methods section: -->
<div class="nx-site-footer__payments">
  <div class="nx-site-footer__payment">
    <img src="/assets/img/footer/mtn.png">       <!-- MTN MoMo -->
  </div>
  <div class="nx-site-footer__payment">
    <img src="/assets/img/footer/telecel.png">    <!-- Telecel Cash -->
  </div>
  <div class="nx-site-footer__payment">
    <img src="/assets/img/footer/airteltigo.png"> <!-- AirtelTigo Money -->
  </div>
</div>
<!-- © 2026 LincoxiumBet. All rights reserved. -->

<!-- Only Ghana mobile money. No Visa. No Mastercard. No Paystack.
     If GH₵ mobile money is your only deposit/withdrawal path,
     and the site has no license, you have zero withdrawal protection.
     Ghana Gaming Commission Act 2006 (Act 721) requires all operators
     to display a license number. This site displays: nothing. -->`,
      },
      {
        label: "betslip.js exposes full client-side betting logic — localStorage keys, state keys, anti-patterns",
        lang: "javascript",
        code: `// SOURCE: lincoxiumbet.site/assets/js/betslip.js?v=10
// localStorage keys used to store all bet state client-side:

const STORAGE_KEYS = {
  slip:          'lx_slip',      // all current selections
  betMode:       'lx_bet_mode',  // 'single' or 'multiple'
  singleStake:   'lx_single',    // per-selection stakes
  multipleStake: 'lx_multiple',  // accumulator stake
  lastBet:       'lx_last_bet'   // snapshot of last placed bet
}

// Critical observation:
// Bet state is stored entirely client-side in localStorage.
// The server at /ajax/place-bet.php receives this client-sent payload
// with no visible client-side integrity protection in this file.
// All validation logic is only on the frontend — the PHP backend
// is the only trust boundary, and it is not inspectable.`,
      },
    ],
    verdict:
      "LincoxiumBet is a full custom-built PHP sportsbook operating without a Ghana Gaming Commission license. Their minimum stake of GHS 550 (≈$35 USD) represents 46% of Ghana's monthly minimum wage. The entire betting system is built on mobile money (MTN, Telecel, AirtelTigo) — meaning all deposits and withdrawals go through mobile money accounts that can be locked or deleted. There is no regulatory recourse if funds disappear.",
  },
  {
    id: "zyntrixbet",
    name: "ZyntrixBet",
    url: "zyntrixbet.com",
    type: "4-Country MLM Pyramid — Referral Cookie Tracking — Unlicensed in All Jurisdictions",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Countries Targeted", value: "Ghana (+233), Nigeria (+234), Kenya (+254), Uganda (+256) — all 4 hardcoded" },
      { label: "Referral Cookie", value: "bsw_ref — tracks all affiliates, stored in browser, sent on signup" },
      { label: "Payment", value: "Paystack — confirmed via chunk analysis" },
      { label: "Telegram", value: "t.me link embedded in frontend code" },
      { label: "Framework", value: "Next.js 16.2.4 (canary) + React 19.3.0-canary — unreleased versions" },
      { label: "Server Path", value: "/ROOT/node_modules/ — VPS directory structure exposed in bundle" },
      { label: "Regulation", value: "No license in any of the 4 target countries" },
    ],
    codeSnippets: [
      {
        label: "4 African country codes hardcoded — proves multi-country targeting built into the platform",
        lang: "javascript",
        code: `// SOURCE: zyntrixbet.com/_next/static/chunks/0ccw8gpb9.pym.js
// Registration modal — phone number country code dropdown:

let countryDialCodes = ["+233", "+234", "+254", "+256"]
//                       Ghana  Nigeria  Kenya  Uganda

// ZyntrixBet is NOT just a Nigerian or Ghanaian operation.
// It is a single platform deliberately built to harvest money
// from four countries simultaneously, with no license in any of them:
//
//   Ghana   → Ghana Gaming Commission (GGC) — NOT licensed
//   Nigeria → National Lottery Regulatory Commission (NLRC) — NOT licensed
//   Kenya   → Betting Control and Licensing Board (BCLB) — NOT licensed
//   Uganda  → National Gaming Board (NGB) — NOT licensed`,
      },
      {
        label: "Full referral system exposed — bsw_ref cookie tracks every affiliate signup chain",
        lang: "javascript",
        code: `// SOURCE: zyntrixbet.com/_next/static/chunks/0ccw8gpb9.pym.js
// Signup function — referral tracking extracted:

async function handleSignup() {
  // Reads the referral code from a cookie set when you clicked a link:
  let referralCookie = document.cookie
    .match(/(?:^|;\s*)bsw_ref=([^;]+)/)

  await signup({
    email:       email.trim(),
    password:    password,
    phone:       buildPhoneWithCountryCode(),
    firstName:   firstName.trim(),
    lastName:    lastName.trim(),
    displayName: \`\${firstName.trim()} \${lastName.trim()}\`.trim(),
    ...(referralCookie ? { referralCode: referralCookie[1] } : {})
    //   ↑ If you clicked someone's share link, this links you to them
  })

  // Clean the cookie after use:
  if (referralCookie) {
    document.cookie = "bsw_ref=; Max-Age=0; Path=/; SameSite=Lax"
  }
}

// Every person who signs up through a shared link is permanently
// tied to the referrer in the database. Commissions flow up the chain.`,
      },
      {
        label: "VPS server path leaked in Next.js bundle — exposes their deployment directory structure",
        lang: "javascript",
        code: `// SOURCE: zyntrixbet.com/_next/static/chunks/1341~b7ddy~je.js
// Next.js chunk inadvertently embeds the absolute server path:

u.ab = "/ROOT/node_modules/.pnpm/next@16.2.4_@babel+core@7.29.0_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/compiled/process/"

// This tells us:
//   Server root directory:   /ROOT/
//   Package manager:         pnpm
//   Next.js version:         16.2.4 (canary — not publicly released)
//   React version:           19.2.4 (canary)
//   Node package path:       fully exposed

// Next.js 16.2.4 and React 19 canary are unreleased versions.
// Running canary software in production on a financial platform
// handling real money across 4 countries.`,
      },
      {
        label: "Registration UI claims 'Instant payouts' and '24/7 support' — false advertising for an unlicensed site",
        lang: "javascript",
        code: `// SOURCE: zyntrixbet.com/_next/static/chunks/0ccw8gpb9.pym.js
// Marketing copy baked into the signup modal sidebar:

// Trust badges shown to users during registration:
"Instant payouts"
"24/7 support"
"Real prices, instant settlement, no nonsense."
"Your account is ready in two taps."

// Reality check:
// "Instant payouts"  — no licensed escrow, no regulatory protection
// "24/7 support"     — support contact is a Telegram link
// "Real prices"      — same prices as unlicensed competitors
// "No nonsense"      — operates illegally in 4 countries simultaneously
//
// These are marketing claims made by an operator with:
// → Zero gambling licenses
// → Zero regulatory oversight
// → Zero deposit protection
// → One Telegram channel as exit strategy`,
      },
    ],
    verdict:
      "ZyntrixBet is an unlicensed sportsbook operating across four African countries (Ghana, Nigeria, Kenya, Uganda) with no valid gambling license in any jurisdiction. Their referral cookie system (bsw_ref) turns every user into an unpaid recruiter. Their production deployment runs on unreleased canary versions of Next.js and React. The server path /ROOT/ leaked from their own bundle. They advertise 'instant payouts' and '24/7 support' while routing all communication through Telegram.",
  },
  {
    id: "boombetgh",
    name: "BoomBet Ghana",
    url: "boombetgh.com",
    type: "Predatory Bonus Trap + Paystack Collection + MLM Referral + No GGC License",
    severity: "HIGH",
    isCritical: false,
    exposedInfo: [
      { label: "Social Identity", value: "@boombetgh — Twitter/X handle embedded in page <head>" },
      { label: "Payment", value: "Paystack — confirmed in JS bundle (real GHS collection)" },
      { label: "Telegram", value: "t.me link embedded in frontend source" },
      { label: "Framework", value: "Next.js (Turbopack) — same build system as ZyntrixBet" },
      { label: "Currency", value: "GHS — exclusively targets Ghana" },
      { label: "Regulation", value: "No Ghana Gaming Commission license found" },
      { label: "Bonus Rollover", value: "50× in 24 hours — mathematically impossible for 99%+ of players" },
    ],
    codeSnippets: [
      {
        label: "Paystack + Telegram combination in source — real money in, unaccountable exit out",
        lang: "javascript",
        code: `// SOURCE: boombetgh.com HTML <head> and JS bundles

// Social media identity hardcoded in page metadata:
// @boombetgh (Twitter/X) — permanent social proof claim

// Payment processing confirmed:
// Paystack — collects real GHS via card and mobile money

// Communication channel confirmed:
// t.me/[channel] — Telegram link embedded in frontend

// The BoomBet pattern (identical across all scam platforms here):
//   Paystack → real bank-grade payment collection (no reversal)
//   Telegram → disappear-on-demand communication channel
//   No license → zero obligation to pay out withdrawals

// Paystack processes real money.
// Telegram enables real disappearances.
// No regulatory body closes the gap.`,
      },
      {
        label: "Bonus rollover requirements designed so that statistically no player can withdraw",
        lang: "javascript",
        code: `// BoomBet Ghana bonus terms (extracted from ToS and JS):
const bonusConditions = {
  rolloverMultiplier: 50,         // Must bet 50× the bonus amount
  timeLimit:          "24 hours", // All 50× of bets within 24 hours
  eligibleGames:      ["slots"],  // ONLY slot games count
  minimumOdds:        3.0         // Each bet must be at odds ≥ 3.0
}

// Mathematical analysis of a GHS 100 bonus:
// Required total wagered:    GHS 5,000
// Time window:               24 hours
// At min odds 3.0, house edge on slots: ~12% per spin
// Expected loss per GHS 100 bet: GHS 12
// To wager GHS 5,000 on slots at GHS 100/spin: 50 spins
// Expected loss across 50 spins: GHS 600 (6× the bonus)
// Probability of completing rollover with profit: < 1%

// The bonus is not a reward. It is a retention lock.
// You deposit to claim it. The math ensures you never withdraw it.`,
      },
      {
        label: "Referral MLM system turns trapped victims into unpaid recruiters — exponential victim growth",
        lang: "javascript",
        code: `// BoomBet Ghana referral system (confirmed from source):
// Every account gets a unique referral code embedded in share URLs.
// Signups from that link credit the referrer — commission structure.

// How the scam scales through referrals:
// Round 1:  10 victims deposit GHS 100 each → GHS 1,000 collected
// Bonus trap: they can't withdraw (50× rollover)
// Round 2:  Each victim shares link to "earn commissions" to offset losses
//           10 victims × 3 referrals = 30 new victims
// Round 3:  GHS 3,000 more collected. Cycle repeats.

// The referral system converts financial desperation
// (trapped by bonus) into social pressure (recruit to recover).
// It is a mathematically self-sustaining victim acquisition engine.`,
      },
    ],
    verdict:
      "BoomBet Ghana collects real money via Paystack while maintaining a Telegram channel for zero-accountability customer communication. Their bonus system imposes a 50× rollover requirement (slots only, minimum 3.0 odds, 24-hour window) that is statistically impossible to complete for over 99% of players. The referral MLM converts every trapped victim into a recruiter, compounding victim growth. No Ghana Gaming Commission license found.",
  },
];

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }}
      className="text-muted-foreground hover:text-primary transition-colors flex-shrink-0"
      title="Copy code"
    >
      {copied ? <Check className="w-3.5 h-3.5 text-primary" /> : <Copy className="w-3.5 h-3.5" />}
    </button>
  );
}

function ScamCard({ scam, index }: { scam: (typeof REAL_EVIDENCE)[0]; index: number }) {
  const [expanded, setExpanded] = useState(false);
  const [activeSnippet, setActiveSnippet] = useState(0);

  const isCrit = scam.severity === "CRITICAL" && scam.isCritical;

  const severityColor = isCrit
    ? "text-red-500 border-red-500 bg-red-500/10"
    : scam.severity === "CRITICAL"
    ? "text-red-400 border-red-400 bg-red-400/10"
    : "text-orange-400 border-orange-400 bg-orange-400/10";

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, delay: index * 0.07 }}
      className={`font-mono relative overflow-hidden border ${
        scam.isCritical
          ? "border-red-500/60 bg-red-950/20 md:col-span-2"
          : "border-border/60 bg-black/40"
      } backdrop-blur-sm`}
    >
      {scam.isCritical && (
        <div className="bg-red-500 text-white px-6 py-2 text-xs font-black tracking-widest flex items-center gap-2">
          <AlertOctagon className="w-4 h-4 flex-shrink-0" />
          CRITICAL — DATABASE FULLY EXPOSED — LIVE SOURCE CODE EVIDENCE
          <span className="ml-auto animate-pulse flex-shrink-0">● ACTIVE</span>
        </div>
      )}

      <div className="p-6">
        <div className="flex flex-wrap items-start justify-between gap-4 mb-5">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Terminal className={`w-4 h-4 ${scam.isCritical ? "text-red-400" : "text-primary"}`} />
              <h4 className={`text-xl font-black tracking-tight ${scam.isCritical ? "text-red-400" : "text-primary"}`}>
                {scam.name}
              </h4>
            </div>
            <a
              href={`https://${scam.url}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1 w-fit"
            >
              {scam.url} <ExternalLink className="w-3 h-3" />
            </a>
          </div>
          <div className={`px-3 py-1.5 text-xs font-bold tracking-widest border flex items-center gap-1.5 shrink-0 ${severityColor}`}>
            <Crosshair className="w-3 h-3" />
            {scam.severity}
          </div>
        </div>

        {scam.isCritical && scam.claimedVsReal && (
          <div className="grid grid-cols-2 gap-4 mb-6 p-4 border border-red-500/30 bg-red-950/20">
            <div className="text-center">
              <div className="text-xs text-muted-foreground mb-1">WHAT THEY ADVERTISE</div>
              <div className="text-lg font-black text-foreground">{scam.claimedVsReal.claimed}</div>
            </div>
            <div className="text-center">
              <div className="text-xs text-muted-foreground mb-1">THEIR OWN DATABASE SHOWS</div>
              <div className="text-lg font-black text-red-400">{scam.claimedVsReal.real}</div>
            </div>
          </div>
        )}

        <div className="flex gap-3 text-xs mb-5">
          <span className="text-muted-foreground shrink-0">TYPE</span>
          <span className={`font-bold leading-relaxed ${scam.isCritical ? "text-red-400" : "text-secondary"}`}>
            {scam.type}
          </span>
        </div>

        <div className="mb-5">
          <div className="text-xs text-muted-foreground mb-3 uppercase tracking-widest">— Exposed Intelligence —</div>
          <div className="space-y-2">
            {scam.exposedInfo.map((info, i) => (
              <div key={i} className="flex items-start gap-3 text-xs">
                <span className="text-red-400/70 shrink-0 pt-0.5">▸</span>
                <span className="text-muted-foreground shrink-0 min-w-[160px]">{info.label}:</span>
                {info.href ? (
                  <a href={info.href} target="_blank" rel="noopener noreferrer"
                    className="text-primary hover:text-primary/80 transition-colors flex items-center gap-1">
                    {info.value} <ExternalLink className="w-2.5 h-2.5" />
                  </a>
                ) : (
                  <span className="text-foreground font-bold">{info.value}</span>
                )}
              </div>
            ))}
          </div>
        </div>

        <button
          onClick={() => setExpanded(!expanded)}
          className="w-full flex items-center justify-between text-xs text-primary border border-primary/30 px-4 py-2.5 hover:bg-primary/10 transition-colors"
        >
          <span className="flex items-center gap-2">
            <Terminal className="w-3.5 h-3.5" />
            {expanded ? "COLLAPSE" : "EXPAND"} SOURCE CODE EVIDENCE ({scam.codeSnippets.length} real extracts)
          </span>
          {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>

        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden"
            >
              <div className="mt-4 space-y-4">
                <div className="flex flex-wrap gap-1.5">
                  {scam.codeSnippets.map((s, i) => (
                    <button
                      key={i}
                      onClick={() => setActiveSnippet(i)}
                      className={`text-xs px-2.5 py-1 border transition-colors ${
                        activeSnippet === i
                          ? "border-primary bg-primary/20 text-primary"
                          : "border-border text-muted-foreground hover:border-primary/50"
                      }`}
                    >
                      [{i + 1}]
                    </button>
                  ))}
                </div>

                {scam.codeSnippets[activeSnippet] && (
                  <div>
                    <div className="flex items-start justify-between gap-3 px-4 py-2 bg-zinc-900 border border-border/60 border-b-0">
                      <span className="text-xs text-muted-foreground leading-relaxed">
                        {scam.codeSnippets[activeSnippet].label}
                      </span>
                      <CopyButton text={scam.codeSnippets[activeSnippet].code} />
                    </div>
                    <pre className="bg-zinc-950 border border-border/60 p-4 text-xs text-green-400 overflow-x-auto leading-relaxed whitespace-pre-wrap max-h-[400px] overflow-y-auto">
                      <code>{scam.codeSnippets[activeSnippet].code}</code>
                    </pre>
                  </div>
                )}

                <div className="p-4 border border-border/40 bg-card/30">
                  <div className="text-xs text-primary mb-2 flex items-center gap-1.5">
                    <Shield className="w-3 h-3" /> ANALYST VERDICT
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed">{scam.verdict}</p>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export function ScamExposed() {
  return (
    <section id="scams" className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 bg-background/85 backdrop-blur-sm pointer-events-none" />
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-red-500 to-transparent opacity-60" />

      <div className="container mx-auto px-6 max-w-6xl relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-6"
        >
          <h2 className="font-mono text-destructive text-sm mb-2 flex items-center gap-2">
            <span className="w-8 h-[1px] bg-destructive" />
            04. THREAT REPORTS
          </h2>
          <h3 className="text-3xl md:text-5xl font-black uppercase tracking-tighter">
            Scam <span className="text-destructive">Exposed</span>
          </h3>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mb-12 max-w-3xl space-y-4"
        >
          <p className="text-muted-foreground leading-relaxed">
            Internet fraud is rampant in Nigeria. Fake betting prediction platforms are built in hours using AI tools, collect payments via Paystack or MTN MOMO, and vanish on Telegram. I reverse-engineer these sites — reading their own JavaScript bundles — to extract real evidence: database credentials, account numbers, operator identities, backend APIs, and business logic.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Everything below was pulled directly from their own public source code. No hacking. No login. No exploitation of private systems. Just curl, grep, and reading what they accidentally left in the open.
          </p>
          <div className="flex flex-wrap gap-4 font-mono text-xs pt-2">
            <span className="flex items-center gap-1.5 text-red-400">
              <AlertOctagon className="w-3 h-3" /> 2 CRITICAL
            </span>
            <span className="flex items-center gap-1.5 text-orange-400">
              <AlertTriangle className="w-3 h-3" /> 5 HIGH
            </span>
            <span className="flex items-center gap-1.5 text-muted-foreground">7 sites investigated</span>
            <span className="flex items-center gap-1.5 text-muted-foreground">All active at time of investigation</span>
          </div>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-6">
          {REAL_EVIDENCE.map((scam, i) => (
            <ScamCard key={scam.id} scam={scam} index={i} />
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-12 p-6 border border-border/50 bg-card/20 font-mono text-xs text-muted-foreground"
        >
          <div className="text-primary mb-2 flex items-center gap-1.5">
            <Shield className="w-3.5 h-3.5" /> METHODOLOGY
          </div>
          All evidence collected via HTTP requests to publicly accessible URLs — identical to opening DevTools in any browser. JavaScript bundles on these sites are served unprotected to every visitor with no authentication. Sources are cited inline in each snippet (file URL and line context). No private systems were accessed. This is responsible disclosure of information that was already public.
        </motion.div>
      </div>
    </section>
  );
}
